name: Code formatting

#on: pull_request_review
on:
  pull_request:
    branches: 
      - main
  
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # check out HEAD on the branch
          ref: ${{ github.head_ref }}
          # make sure the parent commit is grabbed as well, because
          # that's what will get formatted (i.e. the most recent commit)
          fetch-depth: 2
          
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channel-priority: true
          mamba-version: "*"
          python-version: 3.6
        
      - shell: bash -l {0}
        run: |
          mamba install clang-tools -c conda-forge
          git-clang-format HEAD^
          
      # commit the changes (if there are any)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 🎨 apply clang-format changes
          branch: ${{ github.head_ref }}
